"""Embedded command + script content for install-omp-commands."""

CLINE_AUTH_COMMAND_MD = r"""# Cline Auth Command

Verify and repair Cline provider authentication. Uses scripts in ~/.omp/scripts/.

## Arguments

- `$ARGUMENTS` — optional flags:
  - `--force` — force re-auth even if token appears valid
  - `--quiet` — suppress status output
  - `--sync` — sync token to OMP env after check

## Steps

### 1. Check auth health

```bash
bash ~/.omp/scripts/cline-auth-check.sh $ARGUMENTS
```

### 2. If re-auth succeeded, sync token to OMP

```bash
bash ~/.omp/scripts/cline-auth-sync.sh
```

### 3. Verify

```bash
bash ~/.omp/scripts/cline-auth-check.sh --quiet && echo "OK" || echo "FAILED"
```
"""

CLINE_AUTH_CHECK_SH = r"""#!/usr/bin/env bash
set -euo pipefail
PROVIDERS_FILE="$HOME/.cline/data/settings/providers.json"
FORCE=false; QUIET=false
for arg in "$@"; do case "$arg" in
    --force) FORCE=true ;; --quiet) QUIET=true ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
esac; done
log(){ $QUIET || echo "[cline-auth] $*"; }
warn(){ echo "[cline-auth] WARN: $*" >&2; }
err(){ echo "[cline-auth] ERROR: $*" >&2; }
if [[ ! -f "$PROVIDERS_FILE" ]]; then err "providers.json missing"; exit 3; fi
ACCESS_TOKEN=$(bun -e "
 const f=JSON.parse(require('fs').readFileSync('$PROVIDERS_FILE','utf8'));
 const p=f?.providers?.cline?.settings; console.log(p?.auth?.accessToken||'');
" 2>/dev/null) || true
EXPIRE_AT=$(bun -e "
 const f=JSON.parse(require('fs').readFileSync('$PROVIDERS_FILE','utf8'));
 const p=f?.providers?.cline?.settings; console.log(p?.auth?.expiresAt||'0');
" 2>/dev/null) || true
if [[ -z "$ACCESS_TOKEN" ]]; then warn "No access token"; NEEDS_REFRESH=true
else
    NOW_MS=$(date +%s%3N 2>/dev/null || echo $(($(date +%s) * 1000)))
    if [[ "$FORCE" == true ]]; then NEEDS_REFRESH=true; log "Force refresh"
    elif [[ "$EXPIRE_AT" -le "$NOW_MS" ]]; then warn "Token expired"; NEEDS_REFRESH=true
    elif ! echo "$ACCESS_TOKEN" | grep -qi "^workos:"; then warn "Bad prefix"; NEEDS_REFRESH=true
    else
        BUF=$((5 * 60 * 1000))
        if [[ "$EXPIRE_AT" -le $((NOW_MS + BUF)) ]]; then warn "Expiring soon"; NEEDS_REFRESH=true
        else NEEDS_REFRESH=false; fi
    fi
fi
if [[ "$NEEDS_REFRESH" == false ]]; then
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "Authorization: Bearer ${ACCESS_TOKEN}" \
        --max-time 5 "https://api.cline.bot/api/v1/users/me" 2>/dev/null||echo "000")
    if [[ "$HTTP_CODE" == "401" ]]||[[ "$HTTP_CODE" == "000" ]]; then warn "Probe HTTP $HTTP_CODE"; NEEDS_REFRESH=true
    else log "Token valid (HTTP $HTTP_CODE)"; exit 0; fi
fi
log "Triggering re-auth via cline CLI..."
if ! command -v cline &>/dev/null; then err "cline CLI not found"; exit 2; fi
cline auth cline 2>&1 || true
ACCESS_TOKEN=$(bun -e "
 const f=JSON.parse(require('fs').readFileSync('$PROVIDERS_FILE','utf8'));
 const p=f?.providers?.cline?.settings; console.log(p?.auth?.accessToken||'');
" 2>/dev/null) || true
if [[ -n "$ACCESS_TOKEN" ]] && echo "$ACCESS_TOKEN" | grep -qi "^workos:"; then
    log "Re-auth succeeded"; exit 0
fi
warn "Re-auth may need browser. Run 'cline auth' manually."; exit 2
"""

CLINE_AUTH_SYNC_SH = r"""#!/usr/bin/env bash
set -euo pipefail
F="$HOME/.cline/data/settings/providers.json"
E="$HOME/.omp/env"
if [[ ! -f "$F" ]]; then echo "[cline-sync] ERROR: providers.json missing" >&2; exit 1; fi
T=$(bun -e "
 const f=JSON.parse(require('fs').readFileSync('$F','utf8'));
 console.log(f?.providers?.cline?.settings?.auth?.accessToken||'');
" 2>/dev/null) || true
if [[ -z "$T" ]]; then echo "[cline-sync] ERROR: no token" >&2; exit 1; fi
mkdir -p "$(dirname "$E")"
echo "# Generated by cline-auth-sync" > "$E"
echo "export CLINE_USER_KEY=\"${T}\"" >> "$E"
echo "[cline-sync] Token synced to $E"
"""
