"""Install OMP Commands — Cline auth management for Oh My Pi (OMP).

Installs:
  - ~/.omp/agent/commands/cline-auth.md      (slash command for OMP agent)
  - ~/.omp/agent/scripts/cline-auth-check.sh  (token validation + re-auth)
  - ~/.omp/agent/scripts/cline-auth-sync.sh   (token → OMP env sync)
  - ~/.omp/env                                (CLINE_USER_KEY export file)
"""

import json
import sys
from pathlib import Path

from ai_toolkit.install_omp_commands._content import (
    CLINE_AUTH_CHECK_SH,
    CLINE_AUTH_COMMAND_MD,
    CLINE_AUTH_SYNC_SH,
)

CLINE_PROVIDERS = Path.home() / ".cline" / "data" / "settings" / "providers.json"
OMP_MODELS = Path.home() / ".omp" / "agent" / "models.yml"


def _write_file(path: Path, content: str, executable: bool = False) -> bool:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.lstrip("\n"), encoding="utf-8")
        if executable:
            path.chmod(0o755)
        return True
    except OSError as e:
        print(f"Error writing {path}: {e}", file=sys.stderr)
        return False


def _read_cline_token() -> str | None:
    if not CLINE_PROVIDERS.is_file():
        return None
    try:
        data = json.loads(CLINE_PROVIDERS.read_text())
        token = (
            data.get("providers", {})
            .get("cline", {})
            .get("settings", {})
            .get("auth", {})
            .get("accessToken")
        )
        if token and token.startswith("workos:"):
            return token
    except json.JSONDecodeError, KeyError:
        pass
    return None


def install(
    commands_dir: Path | None = None,
    scripts_dir: Path | None = None,
) -> int:
    cmd_dir = commands_dir or Path.home() / ".omp" / "agent" / "commands"
    scr_dir = scripts_dir or Path.home() / ".omp" / "agent" / "scripts"
    failures: list[str] = []

    for name, content, exe in [
        ("cline-auth.md", CLINE_AUTH_COMMAND_MD, False),
        ("cline-auth-check.sh", CLINE_AUTH_CHECK_SH, True),
        ("cline-auth-sync.sh", CLINE_AUTH_SYNC_SH, True),
    ]:
        target = cmd_dir / name if name.endswith(".md") else scr_dir / name
        if not _write_file(target, content, executable=exe):
            failures.append(f"Failed to write {target}")
        else:
            print(f"  {'Command' if name.endswith('.md') else 'Script'}  → {target}")

    token = _read_cline_token()
    if token:
        env_path = Path.home() / ".omp" / "env"
        env = "# Generated by install-omp-commands\n# Source before starting omp\n"
        env += f'export CLINE_USER_KEY="{token}"\n'
        if _write_file(env_path, env):
            print(f"  Env      → {env_path}")
        else:
            failures.append(f"Failed to write {env_path}")
    else:
        print("  (no Cline token found — run 'cline auth cline' first)")

    if failures:
        for f in failures:
            print(f, file=sys.stderr)
        return 1
    print("\nDone. In OMP, use /cline-auth to check & repair auth.")
    return 0


def main() -> int:
    return install()


if __name__ == "__main__":
    sys.exit(main())
